name: Docker Image CI

on:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'freeCodeCamp/devdocs'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile-alpine --tag zhzy0077/devdocs:latest

    - name: Publish the Docker image
      run: docker push zhzy0077/devdocs:latest
